const ALERT='ALERT';
const REFETCH_CHATS=`REFETCH_CHATS`;
const NEW_ATTACHMENT="NEW_ATTCHMENT";
const NEW_MESSAGE_ALERT="NEW_MESSAGE_ALERT"
const NEW_REQUEST_ALERT="NEW_REQUEST_ALERT"
const NEW_MESSAGE="NEW_MESSAGE"

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";
export  { 
    ONLINE_USERS,
    CHAT_JOINED,
    START_TYPING,
    STOP_TYPING,
    CHAT_LEAVED,
    ALERT ,NEW_MESSAGE, REFETCH_CHATS , NEW_ATTACHMENT , NEW_MESSAGE_ALERT  , NEW_REQUEST_ALERT}

    